#!/system/bin/sh
# App Data Keeper (adk) Terminal Toolkit
# Copyright (C) 2018, VR25 @ xda-developers
# License: GPL v3+


modId=adk
modData=/data/media/$modId
logsDir=$modData/logs
logName=terminal
newLog=$logsDir/${logName}.log
oldLog=$logsDir/${logName}_old.log

# prepend Magisk's busybox to PATH
PATH=/sbin/.core/busybox:$PATH

set -u # exit on unset or null variable/parameter
setenforce 0 # sets SELinux mode to "permissive"
umask 000 # default perms (d=rwx-rwx-rwx, f=rw-rw-rw)

# verbose generator
mkdir -p $logsDir 2>/dev/null
[ -f "$newLog" ] && mv $newLog $oldLog
set -x 2>>$newLog

# find modPath
modPath="$(sed -n 's/^.*MOUNTPATH=//p' /data/adb/magisk/util_functions.sh)/$modId"
[ -f $modPath/module.prop ] || { echo -e "\n(!) modPath not found\n"; exit 1; }

. $modPath/core.sh
wizard
