#!/system/bin/sh
# App Data Keeper (adk) APK Restorer
# (c) 2018, VR25 @ xda-developers
# License: GPL v3+


modID=adk
functionName=res_apks
modData=/data/media/$modID

# verbosity engine
logsDir=$modData/logs
newLog=$logsDir/${functionName}_verbose_log.txt
oldLog=$logsDir/${functionName}_verbose_previous_log.txt
[[ -d $logsDir ]] || mkdir -p $logsDir
[[ -f $newLog ]] && mv $newLog $oldLog
set -x 2>>$newLog

modPath=/sbin/.core/img/$modID
[[ -f $modPath/module.prop ]] || modPath=/magisk/$modID
[[ -f $modPath/module.prop ]] || \
  { echo -e "\n(!) modPath not found\n"; exit 1; }

. $modPath/$modID.sh
$functionName
exit 0
