#!/sbin/sh
# App Data Keeper (adk) Rollback'er
# Copyright (C) 2018, VR25 @ xda-developers
# License: GPL v3+


setenforce 0
set -u

getprop | grep zygote | grep -q running && { echo -e "\n(!) Not in recovery mode\n"; exit 1; } 

is_mounted() { mountpoint -q "$1"; }

mount_image() {
  e2fsck -fy $IMG &>/dev/null
  if [ ! -d "$2" ]; then
    mount -o remount,rw /
    mkdir -p "$2"
  fi
  if ! is_mounted $2; then
    for n in 0 1 2 3 4 5 6 7; do
      if (! is_mounted $2); then
        loopDevice=/dev/block/loop$n
        [ -b "$loopDevice" ] || mknod $loopDevice b 7 $n 2>/dev/null
        losetup $loopDevice $1
        [ "$?" -eq "0" ] && mount -t ext4 -o loop $loopDevice $2
        is_mounted $2 && break
      fi
    done
  fi
  if ! is_mounted $mountPoint; then
    echo -e "\n(!) Failed to mount $IMG\n"
    exit 1
  fi
}

mountPoint=/magisk

mount /data 2>/dev/null

[ -d /data/adb/magisk ] && IMG=/data/adb/magisk.img || IMG=/data/magisk.img

if [ ! -d /data/adb/magisk ] && [ ! -d /data/magisk ]; then
  echo -e "\n(!) No Magisk installation found or installed version is not supported\n"
  exit 1
fi

mount_image $IMG $mountPoint

echo
echo -n "\nRevert all changes and uninstall adk (y/N)? "
read ANS

if echo "$ANS" | grep -iq y; then
  echo -e "\nPlease wait...\n"
  for line in $(ls $appData 2>/dev/null); do
    if [ -n "$line" ]; then
      (rm -rf "/data/data/$line" 2>/dev/null
      mv "$appData/$line" /data/data/) &
    fi
  done
  wait
  mv -f $modData/config.txt /sdcard/adk_config_bkp.txt 2>/dev/null
  rm -rf $mountPoint/adk $modData
fi

umount $mountPoint
losetup -d $loopDevice
rmdir $mountPoint
echo -e "- Done.\n"
exit 0
